[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline';
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: blob:;
      font-src 'self';
      connect-src 'self';
      manifest-src 'self';
      worker-src 'self';
    """
    
    # Performance headers
    Cache-Control = "public, max-age=31536000, immutable"

# Cache static assets for 1 year
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache service worker for 1 hour
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Cache manifest for 1 day
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# PWA offline fallback
[[redirects]]
  from = "/offline"
  to = "/offline.html"
  status = 200

# API fallback for development
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Prerender important pages for better SEO
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

# Form handling
[forms]
  settings.enabled = false

# Functions (if needed for future API endpoints)
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"